hpc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
hpc$datetime <- paste(hpc$Date, hpc$Time)
hpc$Date <- dmy(hpc$Date)
lo <- hpc$Date == as.Date("2007-02-01") | hpc$Date == as.Date("2007-02-02")
hpc_data <- subset(hpc, lo)
hpc_data$datetime <- dmy_hms(hpc_data$datetime)
png(filename = "plot2.png", height = 480, width = 480)
with(hpc_data, plot(datetime, Global_active_power, type = "o", pch = ".", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.off()